### ISSUE TITLE
Prey (2017) not detected

### ISSUE THREAD

**Issue by Xarnowit** [mtkennerly/ludusavi#261]
### Ludusavi version

v0.21.0

### Operating system

Windows

### Installation method

Standalone

### Description

Ludusavi doesn't seem to detect Prey (2017) for some reason. I have vague recollection of seeing it on the list in earlier version of the app (didn't do the backup at that time) but I'm not 100% positive so it could be my imagination. Manifest for the game seems to be ok from cursory glance.

Tried CLI with debugging:

`ludusavi.exe backup --preview "Prey (2017)"`

log result (cropped)
```
[2023-08-23T19:39:48.304Z] DEBUG [ludusavi::cli] Invocation: Backup { preview: true, path: None, force: false, merge: false, no_merge: false, update: false, try_update: false, wine_prefix: None, api: false, sort: None, format: None, compression: None, compression_level: None, full_limit: None, differential_limit: None, cloud_sync: false, no_cloud_sync: false, games: ["Prey (2017)"] }
[2023-08-23T19:39:48.886Z] DEBUG [ludusavi::scan::launchers::generic] ranking installations for Steam: G:/SteamGames
[2023-08-23T19:39:48.886Z] DEBUG [ludusavi::scan::launchers::generic] actual install folders: 3DMark | AER | Akane | atomzombiesmasher | Blood | Brigador | Control | Core Keeper | Crush Your Enemies | DeathComing | Desktop Dungeons | Dorfromantik | Dungeon and Puzzles | Fates of Ort | Hades | Halo The Master Chief Collection | Hero's Hour | Heroes of Hammerwatch | HyperLightDrifter | LegendofDungeon | Loop Hero | Lust for Darkness | Mainframe Defenders Test | Moonlighter | MudRunner | Ori and the Will of the Wisps | Pixplode | Plants Vs Zombies | PortalRTX | Prey | Return 2 Games | Revenge of the Titans | Roadwarden | Spyro Reignited Trilogy | Stellaris | Subnautica | Supraland | Tyranny | Waves | Yes, Your Grace | Z
[2023-08-23T19:39:48.886Z] DEBUG [ludusavi::scan::launchers::generic] [Prey (2017)] selecting subdir with score 9223372036854775807: Prey
[2023-08-23T19:39:48.886Z] DEBUG [ludusavi::scan::launchers::generic] ranking installations for Steam: C:/Program Files (x86)\Steam
[2023-08-23T19:39:48.887Z] DEBUG [ludusavi::scan::launchers::generic] actual install folders: Steam Controller Configs | Steamworks Shared
[2023-08-23T19:39:48.887Z] INFO [ludusavi::cli] beginning backup with 1 steps
[2023-08-23T19:39:48.892Z] INFO [ludusavi::cli] completed backup

```

So the app seem to correctly identify game folder but then does nothing:

```
Overall:
  Games: 0
  Size: 0 B
```

### Logs

[ludusavi_rCURRENT.log](https://github.com/mtkennerly/ludusavi/files/12422882/ludusavi_rCURRENT.log)

**Comment by mtkennerly** [comment]
Based on the [PCGamingWiki article](https://www.pcgamingwiki.com/wiki/Prey_(2017)#Game_data), the save data should be under `%USERPROFILE%\Saved Games\Arkane Studios\Prey` (or `Prey_Epic` or `Prey_MS`), not in the game install folder. Could you check if you have that folder and what's in it?

**Comment by Xarnowit** [comment]
Ok I think I found the issue. I think there is inconsistency how special folders (documents, saved games) are detected. I moved `Saved Games` folder using move option from folder properties (it can be used for special folders like documents, saves etc). to `H:\Home\Documents\Saved Games`. `Documents` folder was also moved using this method. In explorer both show normally in in my `%USERPROFILE%`, which is why I didn't notice it initially, but using command line both are missing so I assume explorer is doing some magic behind the scenes to show it in original location.

But, there is other game in that folder that is detected: "Hades" 
So Hades saves location from pcgaming wiki: `"%USERPROFILE%\Documents\Saved Games\Hades\"` and it is detected
while Prey saves location is `%USERPROFILE%\Saved Games\Arkane Studios\Prey` and is not.

Hope that helps

**Comment by mtkennerly** [comment]
Gotcha, that does help.

Ludusavi uses the Windows API to get the correct `%USERPROFILE%` and `%USERPROFILE%\Documents` folders (which is why Hades works even though the documents folder was moved), but not for `%USERPROFILE%\Saved Games`, which I didn't realize was a special folder. I can look into adding some handling for that.

**Comment by Xarnowit** [comment]
Yes, I think `Saved Games` special folder is relatively recent addition. Many games, like Hades, just use  `%USERPROFILE%\Documents` and then append `Saved Games` to the path, which is completely different folder in default installation. It's just happens that I merged both, making it bit more confusing (to debug).

**Comment by sluedecke** [comment]
Is this still an open issue?

Ludusavi seems to properly detect it on my Linux machine (using proton -> using Windows version of Prey).

**Comment by mtkennerly** [comment]
Yeah, this is still an issue, but it should only on Windows itself. Wine prefixes should use the standard name/location, but on Windows, you can move the folder and query the new location from the OS.
